[tool.poetry]
name = "CRISP-DM template"
version = "1.0"
description = "A ready to use template for the CRISP-DM data science workflow"
authors = ["Michael Verdegaal <michaelverdegaal@hotmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
matplotlib = "^3.5.1"
ipykernel = "5.1"
jupyterlab = "^3.4.3"
jupyter = "^1.0.0"
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"

[tool.isort]
profile = "black"
line_length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
